bullet/bullet destroyer 분리 - 실행되지만 error있음..
error
MissingReferenceException: The object of type 'Transform' has been
destroyed but you are still trying to access it.
Your script should
either check if it is null or you should not destroy the
object.
UnityEngine.Transform.get_position () (at
C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineTransformBindings.gen.cs:26)
Bullet.Update
() (at Assets/CS/Bullet.cs:23)